In [1]:
import polars as pl

# URL fixa para o release mais recente (Latest)
BASE_URL = "https://github.com/crdcj/pyield-data/releases/latest/download"

# Para ler o arquivo de ANBIMA TPF
df = pl.read_parquet(f"{BASE_URL}/anbima_tpf.parquet")

df

shape: (70_545, 14)
┌────────────┬──────────┬───────────┬────────────┬───┬──────────┬──────────┬────────────┬──────────┐
│ ReferenceD ┆ BondType ┆ SelicCode ┆ IssueBaseD ┆ … ┆ BidRate  ┆ AskRate  ┆ Indicative ┆ DIRate   │
│ ate        ┆ ---      ┆ ---       ┆ ate        ┆   ┆ ---      ┆ ---      ┆ Rate       ┆ ---      │
│ ---        ┆ str      ┆ i64       ┆ ---        ┆   ┆ f64      ┆ f64      ┆ ---        ┆ f64      │
│ date       ┆          ┆           ┆ date       ┆   ┆          ┆          ┆ f64        ┆          │
╞════════════╪══════════╪═══════════╪════════════╪═══╪══════════╪══════════╪════════════╪══════════╡
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04375  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04344  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000044   ┆ 0.046359 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000056   ┆ 0.050221 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000083   ┆ 0.053607 │
│ …          ┆ …        ┆ …         ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …        │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2018-01-05 ┆ … ┆ 0.13955  ┆ 0.139292 ┆ 0.139401   ┆ 0.13879  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2020-01-10 ┆ … ┆ 0.142873 ┆ 0.142738 ┆ 0.14281    ┆ 0.14111  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2022-01-07 ┆ … ┆ 0.142884 ┆ 0.142778 ┆ 0.142828   ┆ 0.14182  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2024-01-05 ┆ … ┆ 0.14284  ┆ 0.142651 ┆ 0.142743   ┆ 0.14155  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2026-01-09 ┆ … ┆ 0.143048 ┆ 0.142914 ┆ 0.14299    ┆ 0.14149  │
└────────────┴──────────┴───────────┴────────────┴───┴──────────┴──────────┴────────────┴──────────┘

In [ ]:
df = df.with_columns(
    pl.when(pl.col("BondType") == "LFT")
    .then(pl.col("BDToMat") / 252)
    .otherwise("Duration")
    .alias("AvgMaturity")
)

df

shape: (70_545, 15)
┌────────────┬──────────┬───────────┬────────────┬───┬──────────┬───────────┬──────────┬───────────┐
│ ReferenceD ┆ BondType ┆ SelicCode ┆ IssueBaseD ┆ … ┆ AskRate  ┆ Indicativ ┆ DIRate   ┆ AvgMaturi │
│ ate        ┆ ---      ┆ ---       ┆ ate        ┆   ┆ ---      ┆ eRate     ┆ ---      ┆ ty        │
│ ---        ┆ str      ┆ i64       ┆ ---        ┆   ┆ f64      ┆ ---       ┆ f64      ┆ ---       │
│ date       ┆          ┆           ┆ date       ┆   ┆          ┆ f64       ┆          ┆ f64       │
╞════════════╪══════════╪═══════════╪════════════╪═══╪══════════╪═══════════╪══════════╪═══════════╡
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ 0.000023  ┆ 0.04375  ┆ 0.15873   │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ 0.000023  ┆ 0.04344  ┆ 0.662698  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ 0.000044  ┆ 0.046359 ┆ 1.146825  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ 0.000056  ┆ 0.050221 ┆ 1.65873   │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ 0.000083  ┆ 0.053607 ┆ 2.150794  │
│ …          ┆ …        ┆ …         ┆ …          ┆ … ┆ …        ┆ …         ┆ …        ┆ …         │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2018-01-05 ┆ … ┆ 0.139292 ┆ 0.139401  ┆ 0.13879  ┆ 2.434977  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2020-01-10 ┆ … ┆ 0.142738 ┆ 0.14281   ┆ 0.14111  ┆ 3.760811  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2022-01-07 ┆ … ┆ 0.142778 ┆ 0.142828  ┆ 0.14182  ┆ 4.798462  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2024-01-05 ┆ … ┆ 0.142651 ┆ 0.142743  ┆ 0.14155  ┆ 5.583525  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2026-01-09 ┆ … ┆ 0.142914 ┆ 0.14299   ┆ 0.14149  ┆ 6.168733  │
└────────────┴──────────┴───────────┴────────────┴───┴──────────┴───────────┴──────────┴───────────┘

In [5]:
df = df.select(
    "ReferenceDate",
    "BondType",
    "SelicCode",
    "IssueBaseDate",
    "MaturityDate",
    "BDToMat",
    "AvgMaturity",
    "Duration",
    "DV01",
    "DV01USD",
    "Price",
    "BidRate",
    "AskRate",
    "IndicativeRate",
    "DIRate",
)
df

shape: (70_545, 15)
┌────────────┬──────────┬───────────┬────────────┬───┬──────────┬──────────┬────────────┬──────────┐
│ ReferenceD ┆ BondType ┆ SelicCode ┆ IssueBaseD ┆ … ┆ BidRate  ┆ AskRate  ┆ Indicative ┆ DIRate   │
│ ate        ┆ ---      ┆ ---       ┆ ate        ┆   ┆ ---      ┆ ---      ┆ Rate       ┆ ---      │
│ ---        ┆ str      ┆ i64       ┆ ---        ┆   ┆ f64      ┆ f64      ┆ ---        ┆ f64      │
│ date       ┆          ┆           ┆ date       ┆   ┆          ┆          ┆ f64        ┆          │
╞════════════╪══════════╪═══════════╪════════════╪═══╪══════════╪══════════╪════════════╪══════════╡
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04375  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04344  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000044   ┆ 0.046359 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000056   ┆ 0.050221 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000083   ┆ 0.053607 │
│ …          ┆ …        ┆ …         ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …        │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2018-01-05 ┆ … ┆ 0.13955  ┆ 0.139292 ┆ 0.139401   ┆ 0.13879  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2020-01-10 ┆ … ┆ 0.142873 ┆ 0.142738 ┆ 0.14281    ┆ 0.14111  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2022-01-07 ┆ … ┆ 0.142884 ┆ 0.142778 ┆ 0.142828   ┆ 0.14182  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2024-01-05 ┆ … ┆ 0.14284  ┆ 0.142651 ┆ 0.142743   ┆ 0.14155  │
│ 2026-03-13 ┆ NTN-F    ┆ 950199    ┆ 2026-01-09 ┆ … ┆ 0.143048 ┆ 0.142914 ┆ 0.14299    ┆ 0.14149  │
└────────────┴──────────┴───────────┴────────────┴───┴──────────┴──────────┴────────────┴──────────┘

In [5]:
df["ReferenceDate"].unique().sort().tail()

shape: (10,)
Series: 'ReferenceDate' [date]
[
	2026-01-15
	2026-01-16
	2026-01-19
	2026-01-20
	2026-01-21
	2026-01-22
	2026-01-23
	2026-01-26
	2026-01-27
	2026-01-28
]

In [ ]:
from datetime import date

df = df.filter(pl.col("ReferenceDate") != date(2025, 10, 24))
df

shape: (65_876, 14)
┌────────────┬──────────┬───────────┬────────────┬───┬──────────┬──────────┬────────────┬──────────┐
│ ReferenceD ┆ BondType ┆ SelicCode ┆ IssueBaseD ┆ … ┆ BidRate  ┆ AskRate  ┆ Indicative ┆ DIRate   │
│ ate        ┆ ---      ┆ ---       ┆ ate        ┆   ┆ ---      ┆ ---      ┆ Rate       ┆ ---      │
│ ---        ┆ str      ┆ i64       ┆ ---        ┆   ┆ f64      ┆ f64      ┆ ---        ┆ f64      │
│ date       ┆          ┆           ┆ date       ┆   ┆          ┆          ┆ f64        ┆          │
╞════════════╪══════════╪═══════════╪════════════╪═══╪══════════╪══════════╪════════════╪══════════╡
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04375  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000023   ┆ 0.04344  │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000044   ┆ 0.046359 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000056   ┆ 0.050221 │
│ 2020-01-02 ┆ LFT      ┆ 210100    ┆ 2000-07-01 ┆ … ┆ null     ┆ null     ┆ 0.000083   ┆ 0.053607 │
│ …          ┆ …        ┆ …         ┆ …          ┆ … ┆ …        ┆ …        ┆ …          ┆ …        │
│ 2025-10-23 ┆ NTN-F    ┆ 950199    ┆ 2016-01-15 ┆ … ┆ 0.13859  ┆ 0.138388 ┆ 0.138487   ┆ 0.13879  │
│ 2025-10-23 ┆ NTN-F    ┆ 950199    ┆ 2018-01-05 ┆ … ┆ 0.132838 ┆ 0.132643 ┆ 0.13272    ┆ 0.13125  │
│ 2025-10-23 ┆ NTN-F    ┆ 950199    ┆ 2020-01-10 ┆ … ┆ 0.136345 ┆ 0.136228 ┆ 0.136285   ┆ 0.13416  │
│ 2025-10-23 ┆ NTN-F    ┆ 950199    ┆ 2022-01-07 ┆ … ┆ 0.137548 ┆ 0.137301 ┆ 0.137419   ┆ 0.13577  │
│ 2025-10-23 ┆ NTN-F    ┆ 950199    ┆ 2024-01-05 ┆ … ┆ 0.138206 ┆ 0.138063 ┆ 0.138132   ┆ 0.13602  │
└────────────┴──────────┴───────────┴────────────┴───┴──────────┴──────────┴────────────┴──────────┘

In [7]:
df.write_parquet("anbima_tpf.parquet")